ALTER TABLE "pens" DROP CONSTRAINT IF EXISTS "pens_fk0";

ALTER TABLE "pens" DROP CONSTRAINT IF EXISTS "pens_fk1";

ALTER TABLE "pens" DROP CONSTRAINT IF EXISTS "pens_fk2";

ALTER TABLE "inks" DROP CONSTRAINT IF EXISTS "inks_fk0";

ALTER TABLE "inks" DROP CONSTRAINT IF EXISTS "inks_fk1";

ALTER TABLE "inks" DROP CONSTRAINT IF EXISTS "inks_fk2";

ALTER TABLE "paper" DROP CONSTRAINT IF EXISTS "paper_fk0";

ALTER TABLE "paper" DROP CONSTRAINT IF EXISTS "paper_fk1";

ALTER TABLE "paper" DROP CONSTRAINT IF EXISTS "paper_fk2";

ALTER TABLE "accessories" DROP CONSTRAINT IF EXISTS "accessories_fk0";

ALTER TABLE "accessories" DROP CONSTRAINT IF EXISTS "accessories_fk1";

ALTER TABLE "accessories" DROP CONSTRAINT IF EXISTS "accessories_fk2";

DROP TABLE IF EXISTS "pens";

DROP TABLE IF EXISTS "inks";

DROP TABLE IF EXISTS "paper";

DROP TABLE IF EXISTS "accessories";

DROP TABLE IF EXISTS "category";

DROP TABLE IF EXISTS "colors";

DROP TABLE IF EXISTS "sales";

DROP TABLE IF EXISTS "brand";

